name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Prepare virtual environment
        run: make setup

      - name: Run linting checks
        run: make lint

      - name: Execute tests
        run: make test

      - name: Generate simulation artefacts
        run: make simulate

      - name: Exercise baseline pipelines
        run: make baselines

      - name: Produce documentation summary
        run: make docs

      - name: Upload simulation plots
        uses: actions/upload-artifact@v4
        with:
          name: simulation-plots
          path: artefacts/plots
          if-no-files-found: error

      - name: Upload documentation summary
        uses: actions/upload-artifact@v4
        with:
          name: documentation-summary
          path: artefacts/docs
          if-no-files-found: error
